// Entry point for scripts/verify-pure-logic.sh.
fun main() {
    runExifChecks()
    runSynologyChecks()
    runCertPinningChecks()
    runFrameStatsChecks()
    runSourcePolicyChecks()
    runSourceRuntimeSignatureChecks()
    runPlaybackQueueChecks()
    runFolderSelectionSqlChecks()
    runPlaylistSettingsChecks()
    runFolderBalancedPersistentChecks()
    runRememberedWebSecurityChecks()
    runWebPreviewChecks()
    runSourcePoolPolicyChecks()
    runDiagnosticsJsonlChecks()
    runDiagnosticsV2Checks()
    runPrivacyChecks()
    runDiagnosticsRateAndHealthChecks()
    runDiagnosticsPagingAndBundleChecks()
    runRuntimeObservabilityChecks()
    runCrashAndStallChecks()
    runRescanScheduleChecks()
    runWebDavChecks()
    runScanFilterChecks()
    runRecoveryPolicyChecks()
    runHostLifecycleGateChecks()
    runRenderAckRecoveryChecks()
    runPlaybackMemoryPolicyChecks()
    runDecodeColorPolicyChecks()
    runMemorySelfRecoveryChecks()
    runBrightnessTimelineChecks()
    runImageFormatSupportChecks()
    runScanMergePolicyChecks()
    runScanCompletionPolicyChecks()
    runStabilityHardeningChecks()
    println(if (failures == 0) "\nALL CHECKS PASSED" else "\n$failures CHECK(S) FAILED")
    if (failures != 0) kotlin.system.exitProcess(1)
}
