package com.example.familyphotoframe.data.db

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Indexed photo row (spec §6.1). Identity is (sourceId, normalizedPath) via a unique
 * index (spec §6.2); a surrogate autogenerated [id] is the primary key so a rescan of
 * a changed file updates the same logical row.
 *
 * Phase 1 (schema v2) adds decode/cache/curation columns and the remaining §6.2
 * indexes. New NOT NULL columns declare an explicit [ColumnInfo.defaultValue] so the
 * entity schema matches the v1→v2 ALTER statements exactly (Room validates this).
 */
@Entity(
    tableName = "photos",
    indices = [
        Index(value = ["sourceId", "normalizedPath"], unique = true),          // §6.2
        Index(value = ["sourceId", "isHidden", "lastShownAtEpochMs"]),         // §6.2 least-recent
        Index(value = ["stableId"]),
        Index(value = ["sourceId", "dateTakenEpochMs"]),                       // §6.2 (v2)
        Index(value = ["cacheKey"]),                                          // §6.2 (v2)
        Index(value = ["missingSinceEpochMs"]),                               // §6.2 (v2)
        Index(value = ["isFavorite"]),                                        // §6.2 (v2)
        Index(value = ["sourceId", "canonicalDirectory"]),                    // v8 exact folder identity
        Index(value = ["contentSha256"]),                                      // v8 in-folder duplicate suppression
    ],
)
data class PhotoItemEntity(
    @PrimaryKey(autoGenerate = true) val id: Long = 0,
    val stableId: String,
    val sourceId: String,
    val normalizedPath: String,
    val folderName: String,
    val fileName: String,
    val mimeType: String?,
    val sizeBytes: Long,
    val fileModifiedEpochMs: Long,
    val openToken: String,
    val indexedAtEpochMs: Long,
    val isHidden: Boolean = false,
    val lastShownAtEpochMs: Long? = null,
    val decodeFailureCount: Int = 0,
    val lastDecodeFailureAtEpochMs: Long? = null,
    // ---- v2 (Phase 1) additions ----
    val width: Int? = null,
    val height: Int? = null,
    @ColumnInfo(defaultValue = "0") val exifOrientation: Int = 0,
    val dateTakenEpochMs: Long? = null,
    @ColumnInfo(defaultValue = "0") val isFavorite: Boolean = false,
    val missingSinceEpochMs: Long? = null,
    val cacheKey: String? = null,
    // ---- v4 (Phase 2 increment 5) additions: EXIF caption + GPS ----
    /** EXIF `ImageDescription`, trimmed and blank-filtered. Never included in diagnostics. */
    val caption: String? = null,
    /** EXIF GPS latitude/longitude. Never included in diagnostics or redacted exports (§17.2). */
    val gpsLat: Double? = null,
    val gpsLon: Double? = null,
    // ---- v5 (Phase 2 increment 8) ----
    /**
     * When EXIF was last read for this row, or null if it never has been. Null is the
     * queue signal for `ExifBackfiller`: remote photos are indexed without EXIF (see
     * [com.example.familyphotoframe.data.index.ExifScanPolicy]) and filled in on first
     * display. A non-null stamp means "already attempted" even if every field came back
     * null, so a photo genuinely lacking EXIF is not re-opened on every showing.
     */
    val exifScannedAtEpochMs: Long? = null,
    // ---- v8 (FPF-FEAT-SHUFFLE-002 completion) ----
    /** Canonical relative directory that directly contains this photo. */
    @ColumnInfo(defaultValue = "'@root'") val canonicalDirectory: String = "@root",
    /** Lowercase SHA-256 of photo bytes, populated asynchronously outside slideshow rendering. */
    val contentSha256: String? = null,
    /** Successful content-hash completion timestamp; null means not yet indexed. */
    val contentHashScannedAtEpochMs: Long? = null,
)
