package com.example.familyphotoframe.web

/** Embedded stylesheet kept separate from Kotlin routing and browser logic. */
internal object WebUiCss {
    val VALUE: String = """
:root {
  --bg:#eef2f6; --surface:#ffffff; --surface-2:#f7f9fb; --text:#18212f;
  --muted:#627086; --border:#d9e0e8; --accent:#8a5a12; --accent-soft:#f6e6c8;
  --good:#16784a; --warn:#a15c00; --danger:#b42318; --shadow:0 8px 24px rgba(17,31,55,.08);
  font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;
  color-scheme:light;
}
@media (prefers-color-scheme:dark) {
  :root { --bg:#10151d; --surface:#18202b; --surface-2:#202a37; --text:#eef4ff;
    --muted:#aab7ca; --border:#344154; --accent:#e3b23c; --accent-soft:#3a2f18;
    --good:#65d6a2; --warn:#ffc46b; --danger:#ff9289; --shadow:none; color-scheme:dark; }
  /* The bright dark-mode amber needs dark text where it's used as a fill, not white —
     the inverse pairing from light mode's deep amber-brown fill. */
  button.primary,.brand-mark { color:#1a1608; }
}
*{box-sizing:border-box} html,body{margin:0;min-height:100%;background:var(--bg);color:var(--text)}
button,input,select,textarea{font:inherit;max-width:100%} button,input,select,textarea{min-height:44px}
button{border:1px solid var(--border);border-radius:10px;background:var(--surface);color:var(--text);padding:9px 14px;cursor:pointer}
button:hover{border-color:var(--accent)} button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible,a:focus-visible{outline:3px solid color-mix(in srgb,var(--accent) 45%,transparent);outline-offset:2px}
button.primary{background:var(--accent);color:#fff;border-color:var(--accent)} button.danger{background:var(--danger);color:#fff;border-color:var(--danger)} button.ghost{background:transparent}
button:disabled,input:disabled,select:disabled{opacity:.55;cursor:not-allowed}.hidden{display:none!important}
.pair-shell{min-height:100vh;display:grid;place-items:center;padding:20px}.pair-card{width:min(420px,100%);background:var(--surface);border:1px solid var(--border);border-radius:20px;padding:28px;box-shadow:var(--shadow);display:grid;gap:12px}.pair-card h1{margin:0}.pair-card p{margin:0 0 10px;color:var(--muted)}.remember-options{display:grid;gap:10px;padding-top:8px;border-top:1px solid var(--border)}.remember-custom{display:grid;gap:8px}.remember-duration{display:grid;grid-template-columns:1fr 1fr;gap:8px}.warning-box{padding:10px 12px;border:1px solid color-mix(in srgb,var(--warn) 45%,var(--border));border-radius:10px;background:color-mix(in srgb,var(--warn) 8%,var(--surface));color:var(--warn);font-size:12px}
.brand-mark{display:grid;place-items:center;width:54px;height:54px;border-radius:16px;background:var(--accent);color:#fff;font-weight:800;overflow:hidden;flex-shrink:0}.brand-mark img{width:100%;height:100%;object-fit:cover;display:block}.brand-mark.small{width:34px;height:34px;border-radius:10px;font-size:13px}.inline-message{min-height:22px;color:var(--danger)}
.app-shell{min-height:100vh;display:grid;grid-template-columns:230px 1fr;grid-template-rows:68px 1fr;grid-template-areas:"nav header" "nav main"}.nav-rail{grid-area:nav;position:fixed;inset:0 auto 0 0;width:230px;background:var(--surface);border-right:1px solid var(--border);padding:16px 12px;display:flex;flex-direction:column;z-index:30}.brand-row{display:flex;align-items:center;gap:10px;padding:2px 8px 18px}.nav-rail nav{display:grid;gap:4px}.nav-button{width:100%;display:flex;align-items:center;gap:10px;border:0;background:transparent;text-align:left;color:var(--muted)}.nav-button.active{background:var(--accent-soft);color:var(--accent);font-weight:650}.nav-icon{width:22px;text-align:center}.nav-logout{margin-top:auto;background:transparent}
.topbar{grid-area:header;position:sticky;top:0;z-index:20;background:color-mix(in srgb,var(--surface) 94%,transparent);backdrop-filter:blur(12px);border-bottom:1px solid var(--border);display:flex;align-items:center;gap:14px;padding:10px 22px}.topbar-title{display:grid;min-width:0}.status-line{font-size:13px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.topbar-actions{margin-left:auto;display:flex;align-items:center;gap:10px}.save-state{font-size:13px;color:var(--muted)}.badge,.status-badge{display:inline-flex;align-items:center;border:1px solid var(--border);background:var(--surface-2);border-radius:999px;padding:4px 9px;font-size:12px}.status-badge.good{color:var(--good)}.status-badge.warn{color:var(--warn)}.status-badge.bad{color:var(--danger)}
.main-content{grid-area:main;padding:22px;min-width:0}.tab-page{max-width:1500px;margin:0 auto}.page-title{display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:18px}.page-title h1{margin:0;font-size:28px}.page-title p{margin:5px 0 0;color:var(--muted)}
.dashboard-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(300px,.85fr);gap:18px}.stack{display:grid;gap:16px;align-content:start;min-width:0}.card-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(360px,1fr));gap:16px;align-items:start}.card{background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:18px;box-shadow:var(--shadow);min-width:0;overflow-wrap:anywhere}.card h2,.card h3{margin:0 0 6px}.card-description{color:var(--muted);font-size:14px;margin:0 0 16px}.settings-row{display:grid;grid-template-columns:minmax(120px,.85fr) minmax(0,1.15fr);align-items:center;gap:16px;padding:12px 0;border-top:1px solid var(--border);min-width:0}.settings-row:first-of-type{border-top:0}.settings-row>*,.setting-control>*{min-width:0;max-width:100%}.setting-label{display:grid;gap:3px;min-width:0}.setting-label small,.helper{color:var(--muted);font-size:12px}.setting-control{display:flex;align-items:center;justify-content:flex-end;gap:8px;min-width:0;width:100%}.setting-control input:not([type=checkbox]),.setting-control select,.setting-control textarea{width:100%;border:1px solid var(--border);background:var(--surface-2);color:var(--text);border-radius:9px;padding:8px 10px}.setting-control>input:not([type=checkbox]),.setting-control>select,.setting-control>textarea{flex:1 1 0}.setting-control>input[type=range]{flex-basis:120px}.setting-control>.switch-line{flex:0 0 auto}.setting-control textarea{min-height:88px;resize:vertical}.switch-line{display:flex;align-items:center;gap:8px}.switch-line input{width:20px;height:20px}.button-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:14px}.field-error{color:var(--danger);font-size:12px;min-height:16px}.advanced{margin-top:10px;border-top:1px solid var(--border);padding-top:10px}.advanced summary{cursor:pointer;color:var(--accent);font-weight:600;padding:8px 0}
.preview-shell{width:100%;aspect-ratio:16/9;background:#07090d;border-radius:14px;overflow:hidden;position:relative}.preview-shell img{position:absolute;inset:0;width:100%;height:100%;object-fit:contain}.preview-state{position:absolute;inset:0;display:grid;place-items:center;color:#fff;background:rgba(7,9,13,.62);text-align:center;padding:20px}.playback-controls{display:flex;justify-content:center;gap:10px;margin-top:12px}.playback-controls button{min-width:52px}.presentation-meta{display:grid;grid-template-columns:auto 1fr;gap:6px 12px;font-size:13px;margin-top:14px}.presentation-meta dt{color:var(--muted)}.presentation-meta dd{margin:0;overflow-wrap:anywhere}.metric-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px}.metric{background:var(--surface-2);border-radius:12px;padding:12px}.metric strong{display:block;font-size:20px}.metric span{font-size:12px;color:var(--muted)}
.photos-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}.photos-grid .card{width:100%;height:auto;overflow:hidden}.photos-grid .settings-row{grid-template-columns:minmax(145px,.75fr) minmax(220px,1.25fr)}.photos-grid .setting-control>*{min-width:0;max-width:100%}.photos-grid code{display:block;max-width:100%;overflow-wrap:anywhere;word-break:break-word}.photos-folders-card .folder-list{max-height:470px}.photos-maintenance-card{align-self:start}.playback-layout{display:grid;gap:16px}.playback-row{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}.playback-row .card{width:100%;height:auto;overflow:hidden}.playback-layout .settings-row{grid-template-columns:minmax(145px,.72fr) minmax(280px,1.28fr)}.playback-layout .setting-control,.playback-layout .setting-control>*{min-width:0;max-width:100%}.playback-layout .interval-control{width:100%;grid-template-columns:52px minmax(150px,1fr) 52px 92px}.playback-layout .interval-control input[type=number]{min-width:0}.playback-transitions-card .button-row{justify-content:flex-end}.folder-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:10px}.folder-toolbar input[type=search]{flex:1 1 230px;min-width:180px}.folder-toolbar button{flex:0 0 auto}.folder-list{max-height:410px;overflow:auto;border:1px solid var(--border);border-radius:12px}.folder-row{display:grid;grid-template-columns:auto minmax(0,1fr) auto;align-items:center;gap:10px;padding:10px 12px;border-top:1px solid var(--border)}.folder-row:first-child{border-top:0}.folder-row input{width:20px;height:20px}.folder-path{white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.folder-count{color:var(--muted);font-size:12px}
.display-layout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:start}.display-layout .settings-row{grid-template-columns:minmax(140px,.78fr) minmax(0,1.22fr)}.display-layout .setting-control{justify-content:flex-start}.display-layout .brightness-period-row{grid-template-columns:1fr;gap:8px}.brightness-period-control{display:grid;grid-template-columns:minmax(120px,.85fr) minmax(82px,.55fr) minmax(150px,1.2fr);width:100%}
.interval-control{display:grid;grid-template-columns:auto 1fr 82px auto;gap:8px;align-items:center}.interval-control input[type=range]{width:100%}.warning-list,.event-list{display:grid;gap:8px}.warning-item,.event-item{border:1px solid var(--border);border-radius:11px;padding:10px;background:var(--surface-2)}.warning-item button{float:right;min-height:32px;padding:4px 9px}.event-head{display:flex;justify-content:space-between;gap:10px}.event-code{font-weight:650}.event-meta{font-size:12px;color:var(--muted)}.event-fields{font-family:ui-monospace,SFMono-Regular,Consolas,monospace;font-size:12px;white-space:pre-wrap;overflow-wrap:anywhere}.event-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin-bottom:12px}.event-toolbar input,.event-toolbar select{border:1px solid var(--border);background:var(--surface-2);color:var(--text);border-radius:9px;padding:8px 10px}.upload-drop{margin:12px 0;padding:20px;border:2px dashed var(--border);border-radius:14px;text-align:center;color:var(--muted);background:var(--surface-2);cursor:pointer}.upload-drop.dragging,.upload-drop:focus{border-color:var(--accent);color:var(--text);outline:none}.upload-drop strong{display:block;color:var(--text);margin-bottom:4px}
.playback-layout{grid-template-columns:repeat(2,minmax(0,1fr));align-items:start}.playback-column{display:grid;gap:16px;align-content:start;min-width:0}.playback-column .card{width:100%;height:auto;overflow:hidden}.playback-layout .settings-row{grid-template-columns:minmax(125px,.72fr) minmax(0,1.28fr)}.playback-layout .interval-control{grid-template-columns:44px minmax(70px,1fr) 44px minmax(68px,82px)}.device-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;align-items:stretch}.device-summary-grid>.card{height:100%}.web-server-card{margin-top:16px}.remembered-section{margin-top:20px;padding-top:18px;border-top:1px solid var(--border)}.remembered-section h3{margin:0 0 6px}.remember-policy-actions{flex-wrap:nowrap}.remember-policy-actions>button{flex:0 0 auto}.remember-browser-list{margin-top:24px}.remember-browser-list>.event-item{width:100%}.backup-combined .backup-section{padding:4px 0 16px}.backup-combined .backup-section+ .backup-section{border-top:1px solid var(--border);padding-top:18px}.backup-combined input[type=file]{width:100%;margin:10px 0}.event-toolbar{display:grid;gap:10px}.event-actions{display:flex;gap:8px;flex-wrap:wrap;align-items:center}.event-filters{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:8px;min-width:0}.event-filters input,.event-filters select{width:100%;min-width:0}.diagnostic-warnings{display:grid;gap:8px;margin-top:12px}.diagnostic-warnings .warning-box{display:flex;gap:8px;justify-content:space-between;flex-wrap:wrap}.operation-timeline{display:grid;gap:7px;margin:10px 0 14px}.operation-timeline h3{margin:4px 0}.operation-item{border-left:3px solid var(--accent);padding:7px 10px;background:var(--surface-2);border-radius:0 9px 9px 0}.operation-item summary{cursor:pointer;overflow-wrap:anywhere}.event-head{flex-wrap:wrap}.drawer-scrim{position:fixed;inset:0;background:rgba(0,0,0,.45);z-index:25}.toast{position:fixed;right:18px;bottom:18px;z-index:60;background:var(--text);color:var(--surface);padding:12px 16px;border-radius:12px;box-shadow:var(--shadow);max-width:min(420px,calc(100vw - 36px))}dialog{border:0;background:transparent;padding:0}.dialog-card{width:min(480px,calc(100vw - 30px));background:var(--surface);border:1px solid var(--border);border-radius:16px;padding:22px;color:var(--text)}.dialog-card h2{margin-top:0}.dialog-actions{display:flex;justify-content:flex-end;gap:8px}.mobile-only{display:none}.icon-button{padding:7px 10px;background:transparent}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}
.topbar-signout{white-space:nowrap;padding:6px 11px}.web-server-card{width:100%;margin-top:0}.web-server-actions{align-items:center}.diagnostic-device-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;align-items:stretch;margin-bottom:16px}.diagnostic-device-grid>.card{height:100%}.diagnostic-device-grid>.diagnostic-maintenance-card{grid-column:1/-1}.diagnostic-evidence{margin-top:0}
@media(max-width:1199px){.photos-grid{grid-template-columns:1fr}.playback-row{grid-template-columns:1fr}.display-layout{grid-template-columns:1fr}.photos-grid .settings-row,.playback-layout .settings-row{grid-template-columns:minmax(150px,.75fr) minmax(240px,1.25fr)}}
@media(max-width:1199px){.playback-layout{grid-template-columns:1fr}.device-summary-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.device-summary-grid .card:last-child{grid-column:1/-1}}
@media(max-width:1199px){.remember-policy-actions{flex-wrap:wrap}}
@media(max-width:899px){.dashboard-grid{grid-template-columns:1fr}.preview-card{order:-1}}
@media(max-width:899px){.app-shell{display:block}.nav-rail{transform:translateX(-105%);transition:transform .2s ease;width:min(290px,86vw);box-shadow:var(--shadow)}.nav-rail.open{transform:translateX(0)}.topbar{position:sticky;padding:8px 12px}.mobile-only{display:inline-flex}.main-content{padding:14px}.page-title h1{font-size:24px}.settings-row,.photos-grid .settings-row,.playback-layout .settings-row,.display-layout .settings-row{grid-template-columns:1fr;gap:8px}.setting-control{justify-content:flex-start}.card{padding:15px}.interval-control,.playback-layout .interval-control{grid-template-columns:52px minmax(90px,1fr) 52px 78px}.topbar-actions .save-state{display:none}.card-grid,.photos-grid,.playback-row,.display-layout{grid-template-columns:1fr}}
@media(max-width:899px){.device-summary-grid{grid-template-columns:1fr}.device-summary-grid .card:last-child{grid-column:auto}.diagnostic-device-grid{grid-template-columns:1fr}.diagnostic-device-grid>.diagnostic-maintenance-card{grid-column:auto}.event-actions button{flex:1 1 150px}.topbar-signout{padding:6px 9px}}
@media(max-width:599px){.main-content{padding:10px}.card{padding:13px;border-radius:13px}.page-title{align-items:flex-start}.page-title h1{font-size:22px}.topbar-actions{gap:5px}.metric-grid{grid-template-columns:1fr 1fr}.playback-controls{gap:6px}.playback-controls button{padding:8px 10px}.brightness-period-control{grid-template-columns:minmax(0,1fr) minmax(72px,.45fr)}.brightness-period-control select{grid-column:1/-1}.playback-layout .interval-control{grid-template-columns:52px minmax(80px,1fr) 52px;gap:8px}.playback-layout .interval-control [data-action="interval-minus"]{grid-column:1;grid-row:1}.playback-layout .interval-control input[type=range]{grid-column:2;grid-row:1}.playback-layout .interval-control [data-action="interval-plus"]{grid-column:3;grid-row:1}.playback-layout .interval-control input[type=number]{grid-column:1/-1;grid-row:2;width:100%}}
@media(prefers-reduced-motion:reduce){*,*::before,*::after{scroll-behavior:auto!important;transition:none!important;animation:none!important}}
""".trimIndent()
}
